### ISSUE TITLE
error when wanting to create a chart

### ISSUE THREAD

**Issue by leo4444** [morrisjdev/ng-apexcharts#2]
After following the installation steps, I added the following:

HTML: 
  <apx-chart #chartObj> </apx-chart>

TS: 
   import {ChartComponent} from 'ng-apexcharts';

myClass() {
  @ViewChild('chartObj') charter: ChartComponent;

  anyFunc() {
    const options = { ....... }
    const chart = new ApexCharts(this.charter, options);
    chart.render();
 }
}

The error I have is the following:
![captura](https://user-images.githubusercontent.com/17723419/52635522-dd147680-2ea8-11e9-88f6-a8d76e818497.PNG)

Any idea what is happening? I already loaded the scripts to angular.json and imported NgApexchartsModule in my module:
import {NgApexchartsModule} from 'ng-apexcharts';

From already thank you very much!

**Comment by morrisjdev** [comment]
The error occurs because of missing configuration.

You need to insert the configuration using the given attributes of the components.

Example for a line chart:

``` html
<apx-chart #chart [series]="[{name: 'test', data: [1, 2, 3]}]"
           [xaxis]="{ categories: [1, 2, 3] }"
           [chart]="{
              height: 350,
              type: 'line',
              zoom: {
                enabled: false
              },
              shadow: {
                    enabled: true,
                    color: '#000',
                    top: 18,
                    left: 7,
                    blur: 10,
                    opacity: 1
                }}"

  [grid]="{
    row: {
      colors: ['#f3f3f3', 'transparent'],
      opacity: 0.5
    }
  }"
   [title]="{ text: 'Product Trends by Month', align: 'left' }"
           [stroke]="{curve: 'straight'}" [dataLabels]="{enabled: false}"></apx-chart>
```

This also calls .render(...).

For just creating a simple chart you do not need to load the ViewChild in your component.

For a working example checkout: https://stackblitz.com/edit/ngapexcharts-demo?file=src%2Fapp%2Fapp.component.html
